org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# --- Versions (verifie la derniere 21.1.x sur https://projects.neoforged.net/neoforged/neoforge) ---
minecraft_version=1.21.1
neoforge_version=21.1.186
# Parchment = noms de parametres lisibles (optionnel mais confortable)
parchment_version=2024.11.17

# --- Identite du mod ---
mod_version=0.1.0
maven_group=net.emeraude
archives_base_name=bulktrade
