pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven { url = 'https://maven.neoforged.net/releases' }
    }
}

plugins {
    // Cache de telechargement partage (accelere les 1ers builds NeoForge)
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

rootProject.name = 'bulk-trade'
